# Ejercicios Feynman-Microbit

## Ejercicio 0: ¿Para qué sirve el siguiente programa? ¿Qué pasa si el valor es 3?
----------------------------------
import random
valor = random.randint(1, 3)

if valor == 1:
    print("1")
elif valor == 2:
    print("2")
else:
    print("X")

```

## Ejercicio 1: ¿Para qué sirve el siguiente programa?¿Qué pasa si el valor es 3?
---------------------------------
let valor = 0
valor = Math.randomRange(1, 3)


if (valor == 1) {  
basic.showLeds(`
            . . # . .
            . . # . .
            . . # . .
            . . # . .
            . . # . .
            `)
} 
else if (valor == 2) {
                 basic.showLeds(`
            # . . . #
            . # . # .
            . . # . .
            . # . # .
            # . . . #
            `)
} 
else {
 basic.showLeds(`
            # # # # #
            . . . . #
            # # # # #
            # . . . .
            # # # # #
            `)
    }
})

## RESPUESTA 1: Este programa como el anterior sirve para devolver valores
con la cosa curiosa siendo que en vez de devolver con “print” manda señales
a la led que dependiendo del número aleatorio se iluminarán de una manera 
o otra, en este caso si el número generado aleatoriamente es 1 solo las
leds de enmedio se activan, si es 2 las leds se activan haciendo una
forma de X, si es 3 (else es 3 por que el rango aleatorio es de 1-3) 
este se activará formando con los leds un dos.

## Ejercicio 2: Contador de pasos básico
-----------------------------
input.onGesture(Gesture.Shake, function () {
    steps += 1
    basic.showString("" + steps)
})
let steps = 0
let Random = 0
steps = 0

## Ejercicio 2: Contador de pasos básico con Python
-----------------------------
def on_gesture_shake():
    global steps
    steps += 1
    basic.show_string("" + str(steps))
input.on_gesture(Gesture.SHAKE, on_gesture_shake)

steps = 0
Random = 0
steps = 0

## Ejercicio 3: Generador de resultados para una quiniela
-----------------------------
def on_button_pressed_a():
    if randint(1, 3) == 1:
        basic.show_leds("""
            . . # . .
            . # # . .
            . . # . .
            . . # . .
            . # # # .
            """)
    elif randint(1, 3) == 2:
        basic.show_leds("""
            . . # . .
            . # . # .
            . . . # .
            . . # . .
            . # # # .
            """)
    else:
        basic.show_leds("""
            . # # . .
            . . . # .
            . # # # .
            . . . # .
            . # # . .
            """)
input.on_button_pressed(Button.A, on_button_pressed_a)
## Ejercicio 3: Máquina del amor - Medidor de compatibilidad amorosa
-----------------------------
def on_button_pressed_b():
    basic.show_number(input.temperature())
    if input.temperature() < 80:
        basic.show_string("COLD")
        basic.show_icon(IconNames.GHOST)
        music.play(music.string_playable("D C E D C D D E ", 120),
            music.PlaybackMode.UNTIL_DONE)
    elif input.temperature() > 80:
        basic.show_string("HOT")
        basic.show_icon(IconNames.HEART)
        music.play(music.string_playable("F A G A B A B C5 ", 120),
            music.PlaybackMode.UNTIL_DONE)
input.on_button_pressed(Button.B, on_button_pressed_b)
